all:
  children:
    backend:
      hosts:
        backend1:
          ansible_host: 3.83.176.19
          ansible_user: ec2-user
    frontend:
      hosts:
        frontend1:
          ansible_host: 54.167.233.92
          ansible_user: ubuntu
